#!/usr/bin/env bash
# Archive unused files out of the reid-observatory repo's published paths.
# Generated by Claude, 10 Aug 2026, from a full cross-reference audit of a clone of
# jc-bb07/reid-observatory (public repo) against src/App.jsx's live tab->file map,
# every public/*.html file's own internal links, and JS fetch() calls.
# Revised same day per James: kept suicidebrief.html, iom_pension_timebomb.html,
# iom-fun-facts-timelines.html, iom-weird-facts-landing.html in public/ (removed from
# this list) — everything under public/rates/ was never touched by this script at all.
#
# WHAT THIS DOES: moves each file below from its current path into _archive/<same path>,
# so the archived copy's path alone tells you exactly where it used to live and what it
# was called. _archive/ sits at the repo root, next to public/ and src/ — Vite only ever
# serves public/'s contents and bundles what src/ imports, so _archive/ is never built,
# never deployed, never publicly reachable. Nothing is deleted.
#
# BEFORE RUNNING: this assumes it's being run from the repo root (where package.json
# lives) in a git working copy with a clean status, so you can review the change with
# `git status` / `git diff --stat` and revert with `git checkout .` if anything looks wrong.
# Uses `git mv` when the file is tracked (keeps its history), falls back to a plain `mv`
# otherwise. Every move is guarded, so re-running this script is safe (already-moved files
# are silently skipped).

set -euo pipefail

if [ ! -f package.json ] || [ ! -d public ] || [ ! -d src ]; then
  echo "Run this from the reid-observatory repo root (package.json / public/ / src/ must exist here)." >&2
  exit 1
fi

mkdir -p _archive

archive_one() {
  local src="$1"
  if [ ! -e "$src" ]; then
    echo "skip (not found): $src"
    return
  fi
  local dest="_archive/$src"
  mkdir -p "$(dirname "$dest")"
  if git ls-files --error-unmatch "$src" >/dev/null 2>&1; then
    git mv -f "$src" "$dest"
  else
    mv "$src" "$dest"
  fi
  echo "archived: $src -> $dest"
}

archive_one 'index.old'
archive_one 'index.reid'
archive_one 'vite.config.js0'
archive_one 'src/App.old'
archive_one 'src/highlights.old'
archive_one 'src/data/iomSchools.js'
archive_one 'src/shared/App.jsx'
archive_one 'src/shared/App.old'
archive_one 'src/shared/main.jsx'
archive_one 'src/shared/crown-dependencies-demographics.jsx'
archive_one 'src/shared/ui.jsx'
archive_one 'src/public/PublicTabs.jsx'
archive_one 'src/public/DemographicsTab.jsx'
archive_one 'src/public/PopulationPyramids.jsx'
archive_one 'public/affordability.old2'
archive_one 'public/Island_Health_Scorecard_Demo.html'
archive_one 'public/current_suiciderates.html'
archive_one 'public/current_suiciderates_1.html'
archive_one 'public/current_suiciderates_3.html'
archive_one 'public/current_suiciderates_6.html'
archive_one 'public/current_unemploymentexplorer.html'
archive_one 'public/current_unemploymentexplorer_1.html'
archive_one 'public/demographics-explorer-r.html'
archive_one 'public/demographics-explorer-u.html'
archive_one 'public/demographics-explorer.old'
archive_one 'public/demographics-explorer.wkd'
archive_one 'public/economic-performance.html'
archive_one 'public/economic-performance.old'
archive_one 'public/economy-explorer-v2.html'
archive_one 'public/economy-explorer.old'
archive_one 'public/economy-explorer.old2'
archive_one 'public/housing-solution.old'
archive_one 'public/housingsolution.old2'
archive_one 'public/iom-economic-mix.html'
archive_one 'public/iom-economic-mix-updated.html'
archive_one 'public/iom-economic-mix.old'
archive_one 'public/iom-weird-mobile.html'
archive_one 'public/iom-three-sector-model.html'
archive_one 'public/iom_headline_vs_real_balance.html'
archive_one 'public/iomg-budget-sankey (2).old'
archive_one 'public/iomg-budget-sankey - Copy.html'
archive_one 'public/iomg-budget-sankey-projection.html'
archive_one 'public/iomg-budget-sankey-v1.html'
archive_one 'public/iomg-budget-sankey.old'
archive_one 'public/iomg-dept-explorer.html'
archive_one 'public/iomg-fiscal-flows-r.html'
archive_one 'public/iomg-sankeyvis1.html'
archive_one 'public/iom_pension_funding_gap_explorer.html'
archive_one 'public/island-that-didnt-grow-lol.html'
archive_one 'public/island-that-didnt-grow-no.html'
archive_one 'public/island-that-didnt-grow.v1'
archive_one 'public/manx-care-benchmark.htmlo'
archive_one 'public/manxcare-budget-sankey.old'
archive_one 'public/manxcare-reviews-tracker.030726'
archive_one 'public/manxcare-reviews-tracker.htmlo'
archive_one 'public/manxcare-reviews-tracker_DESIGN-REFERENCE.html'
archive_one 'public/my-budget.old'
archive_one 'public/nobles-hospital-sim.html'
archive_one 'public/powering-mann.html0'
archive_one 'public/sankey_v4_layout_mockup.html'
archive_one 'public/suicide-rates.lkg'
archive_one 'public/suicide-rates.old'
archive_one 'public/suicidebrief.old'
archive_one 'public/suicidebrief.old2'
archive_one 'public/suicidebrief_3.html'
archive_one 'public/suicidebrief_4.html'
archive_one 'public/suicidebrief_PUBLIC.old'
archive_one 'public/suiciderates_9_sharpened_1.html'
archive_one 'public/suiciderates_9_sharpened_1.BACKUP-2026-07-29.html'
archive_one 'public/webpage_draft_scotland_addition.html'
archive_one 'public/when-to-see-who.old'
archive_one 'public/your-health-your-island.old'
archive_one 'public/braddan-budget-sankey.html'
archive_one 'public/braddan-budget-sankey.html:Zone.Identifier'
archive_one 'public/marown-budget-sankey.html'
archive_one 'public/marown-budget-sankey.html:Zone.Identifier'
archive_one 'public/santon-budget-sankey.html'
archive_one 'public/santon-budget-sankey.html:Zone.Identifier'
archive_one 'public/json/demographics-data.json'
archive_one 'public/alt/iom-foi-2074149-condition-breakdown.html'
archive_one 'public/alt/iom-foi-heart-stroke-admissions.html'
archive_one 'public/alt/iom-political-health-dashboard.html'
archive_one 'public/alt/iom-rcs-surgery-review-2025.html'
archive_one 'public/alt/iomg-budget-sankey-v2.html'
archive_one 'public/alt/iomg-budget-sankey-v3.html'
archive_one 'public/alt/iomg-budget-sankey-v4.html'
archive_one 'public/alt/iomg-budget-sankey-v5.html'
archive_one 'public/alt/iomg-budget-sankey-v6.html'
archive_one 'public/alt/iomg-budget-sankey-v7.html'
archive_one 'public/alt/iomg-budget-sankey-v8.html'
archive_one 'public/alt/manxcare-reviews-tracker.html'
archive_one 'public/alt/nobles-flow-frontend_old.html'
archive_one 'public/alt/testing-menu.html'
archive_one 'public/alt/when-to-see-who.html'
archive_one 'public/islands.old/01_index.html'
archive_one 'public/islands.old/02_public-health.html'
archive_one 'public/islands.old/03_governance.html'
archive_one 'public/islands.old/04_financial.html'
archive_one 'public/islands.old/05_primary-care.html'
archive_one 'public/islands.old/06_secondary-care.html'
archive_one 'public/islands.old/07_tertiary-remoteness.html'
archive_one 'public/islands.old/08_roadmap.html'
archive_one 'public/islands.old/BUILD_LOG.md'
archive_one 'public/pensions/fp.html'
archive_one 'public/pensions/fp.old'
archive_one 'public/pensions/fp.old2'
archive_one 'public/pensions/iom_pension_timebomb.html'
archive_one 'public/pensions/iom_pension_timebomb.old'
archive_one 'public/systems/index.html'
archive_one 'public/systems/plain-language-model.html'
archive_one 'public/systems/plain-language-model_3.html'
archive_one 'public/systems/sd-model-v5.html'
archive_one 'public/systems/donothing-preview.png'
archive_one 'public/systems/summary-card.png'
archive_one 'public/systems/validation-overlay-preview.png'

echo ""
find public src -type d -empty -delete 2>/dev/null || true
echo "Done. Review with: git status"
echo "Then commit, e.g.: git add -A && git commit -m \"Archive unused files to _archive/\""
echo "See _archive/MANIFEST.md for why each file was moved."
